/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cocos2d.h>
/* Header for class DCConfigParams */

#ifndef _Included_DCConfigParams
#define _Included_DCConfigParams
#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_com_dataeye_data_DCConfigParams_updateSuccess(JNIEnv *, jobject obj);

#ifdef __cplusplus
}
#endif

#define DCCONFIGPARAMS_UPDATE_SUCCESS "DCConfigParamsUpdateSuccess"

class DCConfigParams
{
public:
    static void update();
    static const char* getParameterString(const char* key, const char* defaultValue);
    static int getParameterInt(const char* key, int defaultValue);
    static bool getParameterBool(const char* key, bool defaultValue);
};

#endif